### ISSUE TITLE
use CSS background tiles

### ISSUE THREAD

**Issue by alifeee** [lipu-tenpo/liputenpo.org#89]
WIth the change of the header -> #86, colour will be removed from the page

We could add a subtle CSS background pattern to make it look cuter

Some examples are on <https://www.magicpattern.design/tools/css-backgrounds>

Some examples of it on a site are: <https://alifeee.co.uk/sheffield-transformed-graph/>, <https://weeknotes.alifeee.co.uk/>

p.s. we could also switch the site to light mode to match the magazine

thoughts @ngsilverman ?

**Comment by ngsilverman** [comment]
@alifeee personally I'm not a big fan of the background patterns—I think it reduces readability. I do like the idea of switching to light mode, especially since that matches the magazine as you've pointed out. I also agree with the general sentiment of wanting to add color, but I would suggest maybe doing that through illustrations, which is also what the magazine does. I can imagine one in the logo area and on the article pages at least. 🤔

**Comment by alifeee** [comment]
comparison of

background tiling

![image](https://github.com/user-attachments/assets/4fde5303-0b7c-46c7-899c-1f62e13e1710)

no background tiling

![image](https://github.com/user-attachments/assets/50da7a8b-9925-4715-aebf-9ced03cea337)

I can understand your legibility concern. Perhaps, then, we ought to consider colour choices over background patterns 👍
